services:
  - type: web
    name: circadian-rhythm-analysis
    runtime: python
    rootDir: v2
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: PYTHONIOENCODING
        value: utf-8
    plan: free
